### ISSUE TITLE
Negative value for number of images missing

### ISSUE THREAD

**Issue by geezacoleman** [Sydney-Informatics-Hub/Weed-AI#496]
![image](https://user-images.githubusercontent.com/51358498/122303458-33ef4800-cec9-11eb-85f0-d3dcc6d0d804.png)

Not too sure what's happening here - have been trying the deepweeds dataset for a while but I don't think I will be able to upload it.

**Comment by jnothman** [comment]
This is due to a combination of:
* Our changes to `react-images-upload` appear to be allowing the same filename to be recorded as uploaded twice.
* The missing images reporter using subtraction rather than set difference to compare two lists of filenames in https://github.com/Sydney-Informatics-Hub/Weed-AI/blob/253475aaeabbb11dfaa68324919a2284a3a8cf46/search/src/Components/upload/uploader_images.js#L13-L14
