### ISSUE TITLE
Return a list of duplicate image files if found

### ISSUE THREAD

**Issue by geezacoleman** [Sydney-Informatics-Hub/Weed-AI#509]
Instead of showing a generic error indicating duplicate images were found once the dataset has been submitted, would it be possible to return a list of the files that were deemed to be duplicates in a similar fashion to the duplicate process when you try and upload the same file twice?

**Comment by jnothman** [comment]
This would entail more redesign than we can facilitate now, IMO

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Guy Coleman ***@***.***>
Sent: Tuesday, June 22, 2021 2:31:04 PM
To: Sydney-Informatics-Hub/Weed-AI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Sydney-Informatics-Hub/Weed-AI] Return a list of duplicate image files if found (#509)


Instead of showing a generic error indicating duplicate images were found once the dataset has been submitted, would it be possible to return a list of the files that were deemed to be duplicates in a similar fashion to the duplicate process when you try and upload the same file twice?
